name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Elderly Pose Detection
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            build_cmd: create_linux
          - os: macos-latest
            build_cmd: create_mac
          - os: windows-2019
            build_cmd: create_exe

    steps:
      - name: Install Linux dependencies
        if: matrix.config.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk python3-dev

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build executable
        run: uv run task ${{ matrix.config.build_cmd }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: elderly-pose-${{ matrix.config.os }}${{ matrix.config.ext }}
          path: dist/main${{ matrix.config.ext }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            elderly-pose-windows-2019.exe
            elderly-pose-ubuntu-22.04
            elderly-pose-macos-latest
          draft: false
          prerelease: false
