name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Elderly Pose Detection
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            build_cmd: create_linux
            ext: ''
          - os: macos-latest
            build_cmd: create_mac
            ext: ''
          - os: windows-latest
            build_cmd: create_exe
            ext: '.exe'

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            main.py
            constants.py
            runs/pose/train/weights/best.pt
            downloads/YOLOElderlyPose.v2i.yolov11/data.yaml
            pyproject.toml
            uv.lock

      - name: Install Linux dependencies
        if: matrix.config.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk python3-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build executable
        run: uv run task ${{ matrix.config.build_cmd }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: elderly-pose-${{ matrix.config.os }}${{ matrix.config.ext }}
          path: dist/main${{ matrix.config.ext }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: elderly-pose-windows-latest.exe
          path: windows-artifact

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: elderly-pose-ubuntu-22.04
          path: ubuntu-artifact

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: elderly-pose-macos-latest
          path: macos-artifact

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          files: |
            windows-artifact/elderly-pose-windows-2019.exe
            ubuntu-artifact/elderly-pose-ubuntu-22.04
            macos-artifact/elderly-pose-macos-latest
          draft: false
          prerelease: false
